NAME = Zombie

SRC = newZombie.cpp randomChump.cpp Zombie.cpp

MAIN = main.cpp

FLAGS = -Wall -Wextra -Werror -std=c++98

all : ${NAME}

${NAME}:
	c++ ${FLAGS} ${SRC} ${MAIN} -o ${NAME}

fclean :
	rm -rf ${NAME}
